select
  YPXX.ID,
  YPXX.BM,
  YPXX.MC,
  YPXX.JX,
  YPXX.GG,
  YPXX.ZHXS,
  YPXX.SCQYMC,
  YPXX.SPMC,
  YPXX.ZBJG,
  YPXX.JYZT,
  (select DICTINFO.INFO
   from DICTINFO
   where YPXX.JYZT = DICTINFO.DICTCODE AND DICTINFO.TYPECODE = '003') JYZTMC
from YPXX;